### ISSUE TITLE
Homebridge stürzt beim starten ab

### ISSUE THREAD

**Issue by Bankaifan** [SeydX/homebridge-broadband#1]
Seit heute (oder gestern) bekomme ich beim starten der Homebridge diesen Fehler

/usr/local/lib/node_modules/homebridge-broadband/node_modules/speedtest-net/index.js:628
    for (serverIndex = 0; serverIndex < server.length; serverIndex++) {
                                               ^
TypeError: Cannot read property 'length' of undefined
    at gotServers (/usr/local/lib/node_modules/homebridge-broadband/node_modules/speedtest-net/index.js:628:48)
    at /usr/local/lib/node_modules/homebridge-broadband/node_modules/speedtest-net/index.js:107:16
    at /usr/local/lib/node_modules/homebridge-broadband/node_modules/speedtest-net/index.js:301:7
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-broadband/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:180:13)
    at SAXParser.onclosetag (/usr/local/lib/node_modules/homebridge-broadband/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/usr/local/lib/node_modules/homebridge-broadband/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/local/lib/node_modules/homebridge-broadband/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/local/lib/node_modules/homebridge-broadband/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-broadband/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-broadband/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/usr/local/lib/node_modules/homebridge-broadband/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/usr/local/lib/node_modules/homebridge-broadband/node_modules/xml2js/lib/parser.js:354:19)
    at /usr/local/lib/node_modules/homebridge-broadband/node_modules/speedtest-net/index.js:299:5
    at /usr/local/lib/node_modules/homebridge-broadband/node_modules/speedtest-net/index.js:107:16
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-broadband/node_modules/speedtest-net/index.js:175:7)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)

**Comment by seydx** [comment]
Hast du irgendwas geändert gehabt? Fehler scheint im speedtest Modul zu liegen, schaue ich mir nachher Mal genauer an

**Comment by Bankaifan** [comment]
Das hab ich mir auch gedacht.
Aber ich habe nichts geändert. War Freitag das letzte mal dran um von node 8.9 auf node 9.10.0 hochzurüsten. 
Ich teste mal nen reinstall

Das sind meine Versionen 

pi@raspberrypi:~ $ list-versions 
###############################################
Plugin Versionen:
/usr/local/lib
├── homebridge@0.4.38
├── homebridge-broadband@1.0.1
├── homebridge-config-ui-x@3.4.0
├── homebridge-dacp@0.9.1
├── homebridge-fritz@0.6.0
├── homebridge-people@0.6.2
├── homebridge-philipstv-x@0.5.0
├── homebridge-raspberrypi-temperature@0.0.6
├── homebridge-wol@3.2.1
├── homebridge-xiaomi-roborock-vacuum@0.2.1
├── n@2.1.8
└── npm@5.8.0

NPM-Version
5.8.0
Node-Version
v9.10.0

**Comment by Bankaifan** [comment]
Okay - nach dem Reinstall läuft es wieder... was auch immer das war. Sorry für die Aufregeung ^^

**Comment by seydx** [comment]
Ah super, dann schließe ich es Mal ^^
